namespace: protostar
postgresDb: squid
postgresPassword: postgres
postgresUser: postgres
ipfsGateway: https://subsquid-laos.mypinata.cloud/ipfs/
host: indexer.gorengine.com
rpcOwnership: https://rpc.ankr.com/polygon
rpcLaos: wss://rpc.laossun.gorengine.com
laosGlobalConsensus: 0:0x4756c4042a431ad2bbe61d8c4b966c1328e7a8daa0110e9bbd3d4013138a0bd4
laosParachain: 2000
laosPalletInstance: 51