repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  default:
    values:
      - ./environments/dev/values.yaml
  development:
    values:
      - ./environments/dev/values.yaml
  staging:
    values:
      - ./environments/staging/values.yaml

helmfiles:
  {{- range .Values.postgresInstances }}
  - path: 'charts/db/helmfile.yaml'
    values:
      - namespace: {{ $.Values.namespace }}
      - postgresDb: {{ .postgresDb }}
      - postgresPassword: {{ .postgresPassword }}
      - postgresUser: {{ .postgresUser }}
      - pvcName: {{ .pvcName }}
      - podName: {{ .name }}
      - servicePort: {{ .servicePort }}
      - containerPort: {{ .containerPort }}
      - mountPath: {{ .mountPath }}
      - mountName: {{ .mountName }}
{{- end }}
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: "laos-indexer-ownership-processor"
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresDbHost: {{ .Values.postgresDbHost }}
      - postgresPassword: {{ .Values.postgresPassword }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresPort: {{ .Values.postgresPort }}
      - rpcEndpointSecretKey: {{ .Values.rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .Values.laosGlobalConsensus }}
      - laosParachain: {{ .Values.laosParachain }}
      - laosPalletInstance: {{ .Values.laosPalletInstance }}
      - startingBlockOwnership: {{ .Values.startingBlockOwnership }}
      - startingBlockLaos: {{ .Values.startingBlockLaos }}
      - command: "process:prod:ownership_chain"
  - path: 'charts/processor/helmfile.yaml'
    values:
      - name: "laos-indexer-laos-processor"
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresDbHost: {{ .Values.postgresDbHost }}
      - postgresPassword: {{ .Values.postgresPassword }}
      - postgresUser: {{ .Values.postgresUser }}
      - postgresPort: {{ .Values.postgresPort }}
      - rpcEndpointSecretKey: {{ .Values.rpcEndpointSecretKey }}
      - laosGlobalConsensus: {{ .Values.laosGlobalConsensus }}
      - laosParachain: {{ .Values.laosParachain }}
      - laosPalletInstance: {{ .Values.laosPalletInstance }}
      - startingBlockOwnership: {{ .Values.startingBlockOwnership }}
      - startingBlockLaos: {{ .Values.startingBlockLaos }}
      - command: "process:prod:laos"
  - path: 'charts/api/helmfile.yaml'
    values:
      - namespace: {{ .Values.namespace }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresDbHost: {{ .Values.postgresDbHost }}
      - postgresPort: {{ .Values.postgresPort }}
      - postgresPassword: {{ .Values.postgresPassword }}
      - postgresUser: {{ .Values.postgresUser }}
      - host: {{ .Values.host }}

