namespace: protostar
rpcLaos: wss://rpc.laossigma.laosfoundation.io
laosGlobalConsensus: "0:0x77afd6190f1554ad45fd0d31aee62aacc33c6db0ea801129acb813f913e0764f"
laosParachain: "4006"
laosPalletInstance: "51"
indexerInstances:
  - dbPodName: indexer-db-polygon
    postgresDb: squid
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-1
    servicePort: 5432
    containerPort: 5432
    mountPath: /var/lib/postgresql/pvdata
    mountName: indexer-pvc
    ownershipProcessor: indexer-polygon-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/polygon-mainnet
    startingBlockOwnership: "59689828"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerPolygonRpcEndpoint"
    laosProcessor: indexer-laos-processor-polygon
    apiProcessor: indexer-laos-polygon-api
    host: testnet.polygon-indexer.laosnetwork.io
    gqlPort: 4000
  - dbPodName: indexer-db-ethereum
    postgresDb: squid-ethereum
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-ethereum-1
    servicePort: 5433
    containerPort: 5433
    mountPath: /var/lib/postgresql/pvdata2
    mountName: indexer-pvc-ethereum
    ownershipProcessor: indexer-ethereum-processor
    gatewayEndpoint: https://v2.archive.subsquid.io/network/ethereum-mainnet
    startingBlockOwnership: "20365510"
    startingBlockLaos: "1"
    rpcEndpointSecretKey: "indexerEthereumRpcEndpoint"
    laosProcessor: indexer-laos-processor-ethereum
    apiProcessor: indexer-laos-ethereum-api
    host: testnet.ethereum-indexer.laosnetwork.io
    gqlPort: 4000
  - dbPodName: indexer-db-hedera
    postgresDb: squid-hedera
    postgresPassword: postgres
    postgresUser: postgres
    pvcName: pvc-squid-hedera-1
    servicePort: 5434
    containerPort: 5434
    mountPath: /var/lib/postgresql/pvdata3
    mountName: indexer-pvc-hedera
    ownershipProcessor: indexer-hedera-processor
    gatewayEndpoint: https://testnet.hashio.io/api
    startingBlockOwnership: "7333998"
    startingBlockLaos: "67720"
    rpcEndpointSecretKey: "indexerHederaRpcEndpoint"
    laosProcessor: indexer-laos-processor-hedera
    apiProcessor: indexer-laos-hedera-api
    host: testnet.hedera-indexer.laosnetwork.io
    gqlPort: 4000
