releases:
  - name: laos-indexer-processor-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    chart: .
    values:
      - ipfsGateway: {{ .Values.ipfsGateway }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPassword: {{ .Values.postgresPassword }}
