apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '125m'
            limits:
              memory: '512Mi'
              cpu: '1'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: {{ .Values.postgresPort | quote }}
            - name: DB_HOST
              value: {{ .Values.postgresDbHost }}
            - name: PRIVATE_IPFS_GATEWAY
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: indexerIpfsGateway
            - name: DB_PASS
              value: {{ .Values.postgresPassword }}
            - name: DB_USER
              value: {{ .Values.postgresUser }}
            - name: GQL_PORT
              value: {{ .Values.gqlPort | quote }}
          command: ["sqd", "serve:prod"]
          ports:
            - containerPort: {{ .Values.gqlPort }}