apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-indexer-api
  labels:
    app.kubernetes.io/app: laos-indexer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-indexer-api
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-indexer-api
    spec:
      containers:
        - name: laos-indexer-api
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "laos-indexer-db"
            - name: PRIVATE_IPFS_GATEWAY
              value: {{ .Values.ipfsGateway }}   
            - name: DB_PASS
              value: {{ .Values.postgresPassword }}
            - name: DB_USER
              value: {{ .Values.postgresUser }}
            - name: GQL_PORT
              value: "4350"
          command: ["sqd", "serve:prod"]
          ports:
            - containerPort: 4350