apiVersion: v1
kind: Service
metadata:
  name: laos-indexer-api
  labels:
    app.kubernetes.io/app: laos-indexer-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: laos-indexer-api
  ports:
    - port: 4350
      targetPort: 4350
      protocol: TCP
      name: api
  
