apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: {{ .Values.name }}
  ports:
    - port: {{ .Values.gqlPort }}
      targetPort: {{ .Values.gqlPort }}
      protocol: TCP
      name: api
  
