apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-indexer-processor
  labels:
    app.kubernetes.io/app: laos-indexer-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-indexer-processor
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-indexer-processor
    spec:
      containers:
        - name: laos-indexer-processor
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "laos-indexer-db"
            - name: PRIVATE_IPFS_GATEWAY
              value: {{ .Values.ipfsGateway }}   
            - name: DB_PASS
              value: {{ .Values.postgresPassword }}
            - name: RPC_ENDPOINT
              value: {{ .Values.rpcOwnership }}
            - name: RPC_LAOS_ENDPOINT
              value: {{ .Values.rpcLaos }}
          command: ["sqd", "process:prod"]
          ports:
            - containerPort: 3000
