apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "laos-indexer-db"
            - name: DB_PASS
              value: {{ .Values.postgresPassword }}
            - name: DB_USER
              value: {{ .Values.postgresUser }}
            - name: PRIVATE_IPFS_GATEWAY
              value: {{ .Values.ipfsGateway }}   
            - name: RPC_ENDPOINT
              value: {{ .Values.rpcOwnership }}
            - name: RPC_LAOS_ENDPOINT
              value: {{ .Values.rpcLaos }}
            - name: LAOS_GLOBAL_CONSENSUS
              value: {{ .Values.laosGlobalConsensus | quote }}
            - name: LAOS_PARACHAIN
              value: {{ .Values.laosParachain | quote }}
            - name: LAOS_PALLET_INSTANCE
              value: {{ .Values.laosPalletInstance | quote }}
          command: ["sqd", {{ .Values.command }}]
