apiVersion: v1
kind: Service
metadata:
  name: laos-indexer-processor
  labels:
    app.kubernetes.io/app: laos-indexer-processor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: laos-indexer-processor
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: processor
  
