apiVersion: v1
kind: Service
metadata:
  name: laos-indexer-processor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: processor
  selector:
    app: laos-indexer-processor
