apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-indexer-db
  labels:
    app.kubernetes.io/app: laos-indexer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-indexer-db
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-indexer-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: squid
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: indexer-pvc
              mountPath: /var/lib/postgresql/pvdata
      volumes:
        - name: indexer-pvc
          persistentVolumeClaim:
            claimName: indexer-pvc
