apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}
  labels:
    app: {{ .Values.podName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: {{ .Values.podName }}
  selector:
    app.kubernetes.io/app: {{ .Values.podName }}
