apiVersion: v1
kind: Service
metadata:
  name: laos-indexer-db
  labels:
    app: laos-indexer-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/app: laos-indexer-db