releases:
  - name: {{ .Values.podName }}-db-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    chart: .
    values:
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPassword: {{ .Values.postgresPassword }}
      - postgresUser: {{ .Values.postgresUser }}
      - pvcName: {{ .Values.pvcName }}
      - podName: {{ .Values.podName }}
      - servicePort: {{ .Values.servicePort }}
      - containerPort: {{ .Values.containerPort }}
      - mountPath: {{ .Values.mountPath }}
      - mountName: {{ .Values.mountName }}
