releases:
  - name: indexer-release
    namespace: '{{ .Values.namespace }}'
    createNamespace: false
    chart: .
    values:
      - imageTag: {{ .Values.imageTag }}
      - postgresDb: {{ .Values.postgresDb }}
      - postgresPassword: {{ .Values.postgresPassword }}
      - postgresUser: {{ .Values.postgresUser }}
      - host: {{ .Values.host }}
